name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20.12.2'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Start application
        run: npm start &

      - name: Wait for application to start
        run: sleep 5

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          API_URL: "http://localhost:3000/api"
