name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20.12.2"

      - name: Install dependencies
        run: npm install
        working-directory: ./client

      - name: Build project
        run: npm run build
        working-directory: ./client

      - name: Start application
        run: npm start &
        working-directory: ./client
        env:
          API_URL: "https://booking-system-52fbcxat6q-lz.a.run.app/api"
          RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY }}

      - name: Wait for application to start
        run: sleep 5

      - name: Cypress run
        run: npx cypress run
        working-directory: ./client
        env:
          API_URL: "https://booking-system-52fbcxat6q-lz.a.run.app/api"
          NODE_ENV: development
